-- Create Profiles table
create table profiles (
  id uuid references auth.users not null primary key,
  username text unique,
  full_name text,
  avatar_url text,
  bio text,
  location text,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- Create Widgets table
create table widgets (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  type text not null, -- 'social', 'text', 'image'
  content text,
  title text,
  icon text,
  size text default '1x1',
  position integer,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Create Visits table for analytics
create table visits (
  id bigint generated by default as identity primary key,
  source text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable RLS
alter table profiles enable row level security;
alter table widgets enable row level security;
alter table visits enable row level security;

-- Policies
create policy "Public profiles are viewable by everyone." on profiles for select using ( true );
create policy "Users can insert their own profile." on profiles for insert with check ( auth.uid() = id );
create policy "Users can update own profile." on profiles for update using ( auth.uid() = id );

create policy "Widgets are viewable by everyone." on widgets for select using ( true );
create policy "Users can insert their own widgets." on widgets for insert with check ( auth.uid() = user_id );
create policy "Users can update own widgets." on widgets for update using ( auth.uid() = user_id );
create policy "Users can delete own widgets." on widgets for delete using ( auth.uid() = user_id );

create policy "Anyone can insert visits." on visits for insert with check ( true );
